export enum Role {
  SUPER_ADMIN = "SUPER_ADMIN",
  DISTRICT_OFFICER = "DISTRICT_OFFICER",
  PHC_ADMIN = "PHC_ADMIN",
  FIELD_WORKER = "FIELD_WORKER",
  AUDITOR = "AUDITOR"
}

export enum LocationType {
  STATE = "STATE",
  DISTRICT = "DISTRICT",
  BLOCK = "BLOCK",
  PHC = "PHC",
  SUBCENTRE = "SUBCENTRE"
}

export enum TransferStatus {
  RECOMMENDED = "RECOMMENDED",
  APPROVED = "APPROVED",
  DISPATCHED = "DISPATCHED",
  IN_TRANSIT = "IN_TRANSIT",
  RECEIVED = "RECEIVED",
  RECONCILED = "RECONCILED",
  EXCEPTION = "EXCEPTION"
}

export enum AlertSeverity {
  INFO = "INFO",
  WARNING = "WARNING",
  CRITICAL = "CRITICAL"
}
